/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.fms.fileupload.api;

import java.util.Optional;

import javax.servlet.http.HttpServletRequest;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.fasterxml.jackson.databind.ObjectMapper;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import reactor.core.publisher.Mono;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", 
date = "2020-04-25T05:05:49.607+13:25")
@Api(value = "fileUploadAPI", description = "FileUploadAPI for Feedback system")
public interface FileUploadAPI{

	Logger log = LoggerFactory.getLogger(FileUploadAPI.class);

	default Optional<ObjectMapper> getObjectMapper() {
		return Optional.empty();
	}

	default Optional<HttpServletRequest> getRequest() {
		return Optional.empty();
	}

	default Optional<String> getAcceptHeader() {
		return getRequest().map(r -> r.getHeader("Accept"));
	}

	@ApiOperation(value = "", nickname = "apiEventinfo", notes = "upload files for event information", tags = { "outreachFms", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "successful"),
			@ApiResponse(code = 404, message = "failure") })
	@RequestMapping(value = "/fileUploadAPI/eventsInfo", produces = { "application/json" }, method = RequestMethod.POST)
	default Mono<ResponseEntity<String>> apiEventInfo() {
		if (getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
		} else {
			log.warn(
					"ObjectMapper or HttpServletRequest not configured in default FileUploadAPI interface so no example is generated");
		}
		return Mono.just((new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED)));
	}

	@ApiOperation(value = "", nickname = "apiEventSummary", notes = "upload files for event summary ", tags = { "outreachFms", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "successful"),
			@ApiResponse(code = 404, message = "failure") })
	@RequestMapping(value = "/fileUploadAPI/eventSummary", produces = { "application/json" }, method = RequestMethod.POST)
	default Mono<ResponseEntity<String>> apiEventSummary() {
		if (getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
		} else {
			log.warn(
					"ObjectMapper or HttpServletRequest not configured in default FileUploadAPI interface so no example is generated");
		}
		return Mono.just((new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED)));
	}

	@ApiOperation(value = "", nickname = "apiEventnotattended", notes = "upload files for volunteers not attended", tags = { "outreachFms", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "successful"),
			@ApiResponse(code = 404, message = "failure") })
	@RequestMapping(value = "/fileUploadAPI/eventnotAttended", produces = { "application/json" }, method = RequestMethod.POST)
	default Mono<ResponseEntity<String>> participantNotAttended() {
		if (getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
		} else {
			log.warn(
					"ObjectMapper or HttpServletRequest not configured in default FileUploadAPI interface so no example is generated");
		}
		return Mono.just((new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED)));
	}

	@ApiOperation(value = "", nickname = "apiEventunregistered", notes = "upload files for volunteers unregistered", tags = { "outreachFms", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "successful"),
			@ApiResponse(code = 404, message = "failure") })
	@RequestMapping(value = "/fileUploadAPI/eventunRegistered", produces = { "application/json" }, method = RequestMethod.POST)
	default Mono<ResponseEntity<String>> participantUnregisterd() {
		if (getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
		} else {
			log.warn(
					"ObjectMapper or HttpServletRequest not configured in default FileUploadAPI interface so no example is generated");
		}
		return Mono.just((new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED)));
	}
}
